var projectStack = [
  {
    completed:   '2016-05-20',
    projName:    'Pizza Shop',
    projType:    'solo assignment',
    required:    'Provide a corporated sales site tracking shop-by shop daily output, deliveries and drivers needed.',
    narrative1:  'Lorem ipsum fripsum frapsum',
    narrative2:  'Lorem ipsum fripsum frapsum',
    narrative3:  'Lorem ipsum fripsum frapsum',
    graphic:     '/images/projImgs06.png',
    link:        'http://txtincorporated.github.io/3K1PizzaOdyssey',
  },
  {
    completed:   '2016-05-27',
    projName:    'Focus Group Tool',
    projType:    'solo assignment',
    required:    'Furnish a focus group tool allowing users to vote on which product or style images they most prefer.',
    narrative1:  'Lorem ipsum fripsum frapsum',
    narrative2:  'Lorem ipsum fripsum frapsum',
    narrative3:  'Lorem ipsum fripsum frapsum',
    graphic:     '/images/projImgs07.png',
    link:        'http://txtincorporated.github.io/PhotoVote',
  },
  {
    completed:   '2016-06-03',
    projName:    'Touchpoint Tracker',
    projType:    'team project',
    required:    'Develop an app that allows users to manage and monitor how often they connect with personal contacts.',
    narrative1:  'Lorem ipsum fripsum frapsum',
    narrative2:  'Lorem ipsum fripsum frapsum',
    narrative3:  'Lorem ipsum fripsum frapsum',
    graphic:     '/images/projImgs01.png',
    link:        'http://txtincorporated.github.io/KeepTouch',
  },
];
